pipeline:
  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-performance-tests
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch:
        - master
      event:
        - push
  deploy_to_test:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - TEST_NAME
      - TEST_KUBE_NAMESPACE
      - TEST_KUBE_SERVER
      - TEST_KUBE_TOKEN
      - TEST_INTERNAL_CA_URL
      - TEST_NO_LOGGING_URL_PARAMS
      - TEST_NO_LOGGING_BODY
      - TEST_NO_LOGGING_RESPONSE
      - TEST_KEYCLOAK_URL
      - TEST_KEYCLOAK_REALM
      - TEST_KEYCLOAK_SECRET
      - TEST_INT_DOMAIN
      - TEST_EXT_DOMAIN
      - TEST_PROTOCOL
      - TEST_POSTGREST_NAME
      - TEST_SLACK_WEB_HOOK
      - TEST_S3_KMS_KEY_ID
      - TEST_S3_ACCESS_KEY
      - TEST_S3_BUCKET_NAME
      - TEST_AUTH_CLIENT_SECRET
      - TEST_PERF_TEST_SCHEDULE
      - TEST_DB_URL
      - TEST_DB_SCHEMA
      - TEST_DB_USERNAME
      - TEST_DB_PASSWORD
      - TEST_DB_ANON_ROLE
    commands:
      - export NAME=$${TEST_NAME}
      - export KUBE_NAMESPACE=$${TEST_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${TEST_KUBE_SERVER}
      - export KUBE_TOKEN=$${TEST_KUBE_TOKEN}
      - export INTERNAL_CA_URL=$${TEST_INTERNAL_CA_URL}
      - export NO_LOGGING_URL_PARAMS=$${TEST_NO_LOGGING_URL_PARAMS}
      - export NO_LOGGING_BODY=$${TEST_NO_LOGGING_BODY}
      - export NO_LOGGING_RESPONSE=$${TEST_NO_LOGGING_RESPONSE}
      - export KEYCLOAK_URL=$${TEST_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${TEST_KEYCLOAK_REALM}
      - export KEYCLOAK_SECRET=$${TEST_KEYCLOAK_SECRET}
      - export INT_DOMAIN=$${TEST_INT_DOMAIN}
      - export EXT_DOMAIN=$${TEST_EXT_DOMAIN}
      - export PROTOCOL=$${TEST_PROTOCOL}
      - export POSTGREST_NAME=${TEST_POSTGREST_NAME}
      - export SLACK_WEB_HOOK=${TEST_SLACK_WEB_HOOK}
      - export S3_KMS_KEY_ID=${TEST_S3_KMS_KEY_ID}
      - export S3_ACCESS_KEY=${TEST_S3_ACCESS_KEY}
      - export S3_BUCKET_NAME=${TEST_S3_BUCKET_NAME}
      - export AUTH_CLIENT_SECRET=${TEST_AUTH_CLIENT_SECRET}
      - export PERF_TEST_SCHEDULE=${TEST_PERF_TEST_SCHEDULE}
      - export DB_URL=${TEST_DB_URL}
      - export DB_SCHEMA=${TEST_DB_SCHEMA}
      - export DB_USERNAME=${TEST_DB_USERNAME}
      - export DB_PASSWORD=${TEST_DB_PASSWORD}
      - export DB_ANON_ROLE=${TEST_DB_ANON_ROLE}
      - export IMAGE_TAG=${DRONE_BUILD_NUMBER}
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch:
        - master
      event:
        - push
        - deployment
