pipeline:
  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-performance-tests
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch:
        - master
      event:
        - push
  # deploy_to_test:
  #   image: quay.io/ukhomeofficedigital/kd
  #   secrets:
  #     - TEST_NAME
  #     - TEST_KUBE_NAMESPACE
  #     - TEST_KUBE_SERVER
  #     - TEST_KUBE_TOKEN
  #     - TEST_INTERNAL_CA_URL
  #     - TEST_NO_LOGGING_URL_PARAMS
  #     - TEST_NO_LOGGING_BODY
  #     - TEST_NO_LOGGING_RESPONSE
  #     - TEST_KEYCLOAK_URL
  #     - TEST_KEYCLOAK_REALM
  #     - TEST_KEYCLOAK_SECRET
  #     - TEST_INT_DOMAIN
  #     - TEST_EXT_DOMAIN
  #     - TEST_PROTOCOL
  #     - TEST_PRIVATE_UI_NAME
  #   commands:
  #     - export NAME=$${TEST_NAME}
  #     - export KUBE_NAMESPACE=$${TEST_KUBE_NAMESPACE}
  #     - export KUBE_SERVER=$${TEST_KUBE_SERVER}
  #     - export KUBE_TOKEN=$${TEST_KUBE_TOKEN}
  #     - export INTERNAL_CA_URL=$${TEST_INTERNAL_CA_URL}
  #     - export NO_LOGGING_URL_PARAMS=$${TEST_NO_LOGGING_URL_PARAMS}
  #     - export NO_LOGGING_BODY=$${TEST_NO_LOGGING_BODY}
  #     - export NO_LOGGING_RESPONSE=$${TEST_NO_LOGGING_RESPONSE}
  #     - export KEYCLOAK_URL=$${TEST_KEYCLOAK_URL}
  #     - export KEYCLOAK_REALM=$${TEST_KEYCLOAK_REALM}
  #     - export KEYCLOAK_SECRET=$${TEST_KEYCLOAK_SECRET}
  #     - export INT_DOMAIN=$${TEST_INT_DOMAIN}
  #     - export EXT_DOMAIN=$${TEST_EXT_DOMAIN}
  #     - export PROTOCOL=$${TEST_PROTOCOL}
  #     - export PRIVATE_UI_NAME=$${TEST_PRIVATE_UI_NAME}
  #     - export IMAGE_TAG=${DRONE_BUILD_NUMBER}
  #     - kd --insecure-skip-tls-verify -f kube/network-policy.yml
  #     - kd --insecure-skip-tls-verify -f kube/secret.yml
  #     - kd --insecure-skip-tls-verify -f kube/service.yml
  #     - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
  #     - kd --insecure-skip-tls-verify -f kube/ingress.yml
  #   when:
  #     branch:
  #       - master
  #     event:
  #       - push
  #       - deployment
