pipeline:
  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
       event: push

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - source: DEV_PERF_TEST_NAME
        target: NAME
    commands:
      - docker build -t $${NAME}:$${DRONE_COMMIT_SHA} .
    when:
      event:
        - push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - source: QUAY_USERNAME
        target: DOCKER_USERNAME
      - source: QUAY_PASSWORD
        target: DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-performance-tests
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - source: DEV_PERF_TEST_NAME
        target: NAME
      - source: DEV_PERF_TEST_KUBE_NAMESPACE
        target: KUBE_NAMESPACE
      - source: DEV_KUBE_SERVER
        target: KUBE_SERVER
      - source: DEV_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: DEV_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: DEV_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: DEV_PERF_TEST_POSTGREST_NAME
        target: POSTGREST_NAME
      - source: DEV_PERF_TEST_SLACK_WEB_HOOK
        target: SLACK_WEB_HOOK
      - source: DEV_PERF_TEST_S3_KMS_KEY_ID
        target: S3_KMS_KEY_ID
      - source: DEV_PERF_TEST_S3_ACCESS_KEY
        target: S3_ACCESS_KEY
      - source: DEV_PERF_TEST_S3_BUCKET_NAME
        target: S3_BUCKET_NAME
      - source: DEV_PERF_TEST_S3_SECRET_KEY
        target: S3_SECRET_KEY
      - source: DEV_PERF_TEST_AUTH_CLIENT_ID
        target: AUTH_CLIENT_ID
      - source: DEV_PERF_TEST_AUTH_CLIENT_SECRET
        target: AUTH_CLIENT_SECRET
      - source: DEV_PERF_TEST_REFDATA_URL
        target: REFDATA_URL
      - source: DEV_PERF_TEST_REFDATA_BASE_URL
        target: REFDATA_BASE_URL
      - source: DEV_PERF_TEST_REFDATA_USERNAME
        target: REFDATA_USERNAME
      - source: DEV_PERF_TEST_REFDATA_PASSWORD
        target: REFDATA_PASSWORD
      - source: DEV_PERF_TEST_REPORT_BASE_URL
        target: REPORT_BASE_URL
    commands:
      - export IMAGE_TAG=${DRONE_COMMIT_SHA}
    #  - kd --insecure-skip-tls-verify -f kube/ref-data-small-dataset.yml
    #  - kd --insecure-skip-tls-verify -f kube/ref-data-large-dataset.yml
    when:
    #  branch: master
      event: [ push, deployment ]

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
