pipeline:
  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DEV_NAME
    commands:
      - docker build -t $${DEV_NAME}:$${DRONE_COMMIT_SHA} .
    when:
      event:
        - push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/cop-performance-tests
    secrets:
      - DEV_NAME
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/${DEV_NAME}
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch:
#        - master
      event:
        - push
  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_NAME
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_KEYCLOAK_URL
      - DEV_KEYCLOAK_REALM
      - DEV_POSTGREST_NAME
      - DEV_SLACK_WEB_HOOK
      - DEV_S3_KMS_KEY_ID
      - DEV_S3_ACCESS_KEY
      - DEV_S3_BUCKET_NAME
      - DEV_S3_SECRET_KEY
      - DEV_AUTH_CLIENT_ID
      - DEV_AUTH_CLIENT_SECRET
      - DEV_REFDATA_URL
      - DEV_REFDATA_BASE_URL
      - DEV_REFDATA_USERNAME
      - DEV_REFDATA_PASSWORD
      - DEV_REPORT_BASE_URL
    commands:
      - export NAME=$${DEV_NAME}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export KEYCLOAK_URL=$${DEV_KEYCLOAK_URL}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export SLACK_WEB_HOOK=$${DEV_SLACK_WEB_HOOK}
      - export S3_KMS_KEY_ID=$${DEV_S3_KMS_KEY_ID}
      - export S3_ACCESS_KEY=$${DEV_S3_ACCESS_KEY}
      - export S3_BUCKET_NAME=$${DEV_S3_BUCKET_NAME}
      - export S3_SECRET_KEY=$${DEV_S3_SECRET_KEY}
      - export AUTH_CLIENT_SECRET=$${DEV_AUTH_CLIENT_SECRET}
      - export AUTH_CLIENT_ID=$${DEV_AUTH_CLIENT_ID}
      - export REFDATA_URL=$${DEV_REFDATA_URL}
      - export REFDATA_BASE_URL=$${DEV_REFDATA_BASE_URL}
      - export REFDATA_USERNAME=$${DEV_REFDATA_USERNAME}
      - export REFDATA_PASSWORD=$${DEV_REFDATA_PASSWORD}
      - export REPORT_BASE_URL=$${DEV_REPORT_BASE_URL}
      - export IMAGE_TAG=${DRONE_BUILD_NUMBER}
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/ref-data-small-dataset.yml
      - kd --insecure-skip-tls-verify -f kube/ref-data-large-dataset.yml
    when:
      branch:
#        - master
      event:
        - push
        - deployment
