---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.NAME}}
spec:
  selector:
    matchLabels:
      name: {{.NAME}}
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: {{.NAME}}
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: certs
          image: quay.io/ukhomeofficedigital/borders-cfssl-sidekick:bd4901b5a28c
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --domain={{.NAME}}.{{.KUBE_NAMESPACE}}.svc.cluster.local
            - --url={{.INTERNAL_CA_URL}}
            - --verbose=True
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
        - name: proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "50Mi"
              cpu: "100m"
          env:
            - name: PROXY_SERVICE_HOST
              value: "127.0.0.1"
            - name: PROXY_SERVICE_PORT
              value: "8181"
            - name: SERVER_CERT
              value: "/certs/tls.pem"
            - name: SERVER_KEY
              value: "/certs/tls-key.pem"
            - name: SSL_CIPHERS
              value: "ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:AES256+EDH:!aNULL"
            - name: ENABLE_UUID_PARAM
              value: "FALSE"
            - name: NAXSI_USE_DEFAULT_RULES
              value: "FALSE"
            - name: PORT_IN_HOST_HEADER
              value: "FALSE"
            - name: ERROR_REDIRECT_CODES
              value: "599"
            - name: ADD_NGINX_SERVER_CFG
              value: 'gzip off; location = /reload { allow 127.0.0.1; deny all; content_by_lua_block { os.execute("touch /tmp/nginx-reload-triggered; /usr/local/openresty/nginx/sbin/nginx -s reload; touch /tmp/nginx-reload-complete;") } }'
            - name: ADD_NGINX_LOCATION_CFG
              value: |
                gzip off;
                proxy_buffer_size         128k;
                proxy_buffers             4 256k;
                proxy_busy_buffers_size   256k;
                add_header       X-Frame-Options 'ALLOW-FROM {{.PROTOCOL}}{{.PRIVATE_UI_NAME}}.{{.EXT_DOMAIN}}' always;
            - name: LOG_FORMAT_NAME
              value: "json"
            - name: NO_LOGGING_URL_PARAMS
              value: "{{.NO_LOGGING_URL_PARAMS}}"
            - name: NO_LOGGING_BODY
              value: "{{.NO_LOGGING_BODY}}"
            - name: NO_LOGGING_RESPONSE
              value: "{{.NO_LOGGING_RESPONSE}}"
            - name: STATSD_METRICS
              value: "FALSE"
          ports:
            - name: https
              containerPort: 10443
          volumeMounts:
            - name: certs
              mountPath: /certs
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
        - name: {{.NAME}}
          image: quay.io/ukhomeofficedigital/cop-performance-tests:{{.IMAGE_TAG}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          # readinessProbe:
          #   httpGet:
          #     path: /readiness
          #     port: 8181
          #     scheme: HTTP
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8181
          #     scheme: HTTP
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          volumeMounts:
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
          env:
            - name: AUTH_CLIENT_ID
              value: {{.NAME}}
            - name: AUTH_URL
              value: {{.KEYCLOAK_URL}}
            - name: AUTH_REALM
              value: {{.KEYCLOAK_REALM}}
            - name: POSTGREST_DOMAIN
              value: {{.POSTGREST_NAME}}{{.EXT_DOMAIN}}
            - name: POSTGREST_PATH
              value: rf_gender
      volumes:
        - name: bundle
          configMap:
            name: bundle
        - name: certs
          emptyDir: {}
