apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .NAME }}
  namespace: {{ .NAMESPACE }}
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: {{ .PERF_TEST_SCHEDULE }}
  jobTemplate:
   spec:
     backoffLimit: 0
     template:
      spec:
        containers:
          - name: {{.NAME}}
            image: quay.io/ukhomeofficedigital/cop-performance-tests:latest
            env:
              - name: AUTH_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ .NAME }}
                    key: authClientId
              - name: AUTH_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .NAME }}
                    key: authClientSecret
              - name: S3_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .NAME }}
                    key: s3AccessKey
              - name: S3_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: {{ .NAME }}
                    key: s3SecretKey
              - name: S3_KMS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: {{ .NAME }}
                    key: s3KmsKeyId
              - name: S3_BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    name: {{ .NAME }}
                    key: s3BucketName
              - name: POSTGREST_DOMAIN
                value: "{{ .POSTGREST_NAME }}.{{ .EXT_DOMAIN }}"
              - name: POSTGREST_PATH
                value: "/rf_gender"
              - name: KEYCLOCK_DOMAIN
                value: {{ .KEYCLOAK_URL }}
              - name: KEYCLOCK_PATH
                value: "/realms/{{ .KEYCLOAK_REALM }}/protocol/openid-connect/token"
              - name: SLACK_WEB_HOOK
                valueFrom:
                  secretKeyRef:
                    name: {{ .NAME }}
                    key: slackWebHook
            command:
              - /bin/sh
              - -c
              - >
                cd /bzt/scripts
                && ./run-report.sh
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
            resources:
                requests:
                  memory: "2048Mi"
                  cpu: "1000m"
                limits:
                  memory: "4096Mi"
                  cpu: "2000m"
        restartPolicy: Never

