apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .NAME }}
  namespace: {{ .KUBE_NAMESPACE }}
spec:
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: "30 8 * * 1-5"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: {{.NAME }}
              image: quay.io/ukhomeofficedigital/cop-performance-tests:latest
              env:
                - name: AUTH_CLIENT_ID
                  value: {{ .AUTH_CLIENT_ID }}
                - name: AUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .NAME }}
                      key: authClientSecret
                - name: S3_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .NAME }}
                      key: s3AccessKey
                - name: S3_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .NAME }}
                      key: s3SecretKey
                - name: S3_KMS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .NAME }}
                      key: s3KmsKeyId
                - name: S3_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .NAME }}
                      key: s3BucketName
                - name: REFDATA_URL
                  value: {{ .REFDATA_URL }}
                - name: REFDATA_BASE_URL
                  value: {{ .REFDATA_BASE_URL }}
                - name: REPORT_BASE_URL
                  value: {{ .REPORT_BASE_URL }}
                - name: KEYCLOAK_URL
                  value: {{ .KEYCLOAK_URL }}
                - name: KEYCLOAK_PATH
                  value: "/auth/realms/{{ .KEYCLOAK_REALM }}/protocol/openid-connect/token"
                - name: SLACK_WEB_HOOK
                  valueFrom:
                    secretKeyRef:
                      name: {{ .NAME }}
                      key: slackWebHook
                - name: REFDATA_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .NAME }}
                      key: refDataUserName
                - name: REFDATA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .NAME }}
                      key: refDataPassword
                - name: KUBE_NAMESPACE
                  value: {{ .KUBE_NAMESPACE }}
              command:
                - /bin/sh
                - -c
                - >
                  cd /bzt
                  && ./scripts/run-report.sh ref-data-large-dataset
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
              resources:
                requests:
                  memory: "2048Mi"
                  cpu: "1000m"
                limits:
                  memory: "4096Mi"
                  cpu: "2000m"
          restartPolicy: Never

