settings:
  env:
    jmeterVersion: 5.1.1
execution:
  - scenario: ref-data
  - scenario: ref-data-auth
scenarios:
  ref-data:
    script: /bzt/scenarios/ref-data.jmx
  ref-data-auth:
    script: /bzt/scenarios/ref-data-auth.jmx
modules:
    properties:
      jmeter.reportgenerator.apdex_satisfied_threshold: 1000
      jmeter.reportgenerator.report_title: JMeter Taurus Demo
      jmeter.reportgenerator.overall_granularity: 1000
      jmeter.reportgenerator.exporter.html.series_filter: ^(ClickNext|HP|scenario)(-success|-failure)?$
      output: ${TAURUS_ARTIFACTS_DIR}/output/
services:
  - module: shellexec
    post-process:
      - ~/.bzt/jmeter-taurus/${jmeterVersion}/bin/jmeter -p ~/.bzt/jmeter-taurus/${jmeterVersion}/bin/jmeter.properties -q ${TAURUS_ARTIFACTS_DIR}/jmeter-bzt-1.properties -g ${TAURUS_ARTIFACTS_DIR}/output.csv -o ${TAURUS_ARTIFACTS_DIR}/report
reporting:
  - module: final-stats
  - module: console
