settings:
  env:
    jmeterVersion: 5.1.1
execution:
  - scenario: perf-tests
scenarios:
  perf-tests:
    script: /bzt/scenarios/perf-tests.jmx
modules:
  jmeter:
    path: /bzt/jmeter-taurus/${jmeterVersion}/bin/jmeter
    version: ${jmeterVersion}
    properties:
      jmeter.reportgenerator.apdex_satisfied_threshold: 1000
      jmeter.reportgenerator.report_title: JMeter Perf Tests
      jmeter.reportgenerator.overall_granularity: 1000
      jmeter.reportgenerator.exporter.html.series_filter: ^(ClickNext|HP|scenario)(-success|-failure)?$
      output: ${TAURUS_ARTIFACTS_DIR}/output/
services:
  - module: shellexec
    post-process:
      - /bzt/jmeter-taurus/${jmeterVersion}/bin/jmeter -p /bzt/jmeter-taurus/${jmeterVersion}/bin/jmeter.properties -q ${TAURUS_ARTIFACTS_DIR}/jmeter-bzt.properties -g ${TAURUS_ARTIFACTS_DIR}/summary-report.csv -o ${TAURUS_ARTIFACTS_DIR}/report
reporting:
  - module: final-stats
  - module: console
