settings:
  env:
    jmeterVersion: 5.1.1
execution:
  - scenario: perf-tests
scenarios:
  perf-tests:
    script: /bzt/scenarios/ref-data-small-dataset.jmx
modules:
  jmeter:
    path: /bzt/jmeter-taurus/${jmeterVersion}/bin/jmeter
    version: ${jmeterVersion}
    properties:
      output: ${TAURUS_ARTIFACTS_DIR}/output/
services:
  - module: shellexec
    post-process:
      - /bzt/jmeter-taurus/${jmeterVersion}/bin/jmeter -p /bzt/jmeter-taurus/${jmeterVersion}/bin/jmeter.properties -q ${TAURUS_ARTIFACTS_DIR}/jmeter-bzt.properties -g ${TAURUS_ARTIFACTS_DIR}/ref-data-small-dataset.csv -o ${TAURUS_ARTIFACTS_DIR}/report
reporting:
  - module: final-stats
  - module: console
